### ISSUE TITLE
The name "comparator" is already taken

### ISSUE THREAD

**Issue by Wuzzy2** [Neocraft1293/itemquantifiermod#1]
Using "comparator" as a name is a terrible choice because this name is already taken. MCL2 already includes a thing called "Redstone Comparator" (although it's somewhat WIP).

I strongly recommend to rename this mod as well as its items/nodes.

**Comment by Neocraft1293** [comment]
Thank you so much for your constructive feedback. I've carefully considered your suggestion and made the necessary changes. My mod, originally named "Comparator," has been renamed to "Item Quantifier" to avoid any conflicts with the element currently being developed in MCL2, known as the "Redstone Comparator."
